global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: asoboh7@gmail.com
  smtp_auth_username: asoboh7@gmail.com
  smtp_auth_password: "xcux rnei qxgt onvm"
  smtp_require_tls: true

route:
  receiver: gmail_email

receivers:
  - name: gmail_email
    email_configs:
      - to: asoboh7@gmail.com
        send_resolved: true
