global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: ${SMTP_FROM_EMAIL}
  smtp_auth_username: ${SMTP_USERNAME}
  smtp_auth_password: ${SMTP_PASSWORD}
  smtp_require_tls: true

route:
  receiver: gmail_email

receivers:
  - name: gmail_email
    email_configs:
      - to: ${ALERT_EMAIL}
        send_resolved: true
